Repository apollographql/reason-apollo, pull requests merged in 2018-07, with the labels that each got.

#115 Feature/query subscribe to more
  examples/swapi/src/PersonByIdDelete.re
  examples/swapi/src/PersonSubscribeToMore.re
  examples/swapi/src/ShowLivePersons.re
  examples/swapi/src/SubscribeToPersons.re
  package.json
  src/ReasonApolloTypes.re
  src/graphql-types/ReasonApolloQuery.re
Labels: feature

#99 Add UpdateQuery for FetchMore
  examples/swapi/src/PersonByIdDelete.re
  examples/swapi/src/Persons.re
  src/graphql-types/ReasonApolloQuery.re
Labels: blocking

#117 Feature/subscription example
  examples/realtime-chat-application/.gitignore
  examples/realtime-chat-application/README.md
  examples/realtime-chat-application/bsconfig.json
  examples/realtime-chat-application/graphql_schema.json
  examples/realtime-chat-application/package.json
  examples/realtime-chat-application/public/favicon.ico
  examples/realtime-chat-application/public/index.html
  examples/realtime-chat-application/public/manifest.json
  examples/realtime-chat-application/public/notification.mp3
  examples/realtime-chat-application/public/notification.ogg
  examples/realtime-chat-application/src/AddMessage.re
  examples/realtime-chat-application/src/App.re
  examples/realtime-chat-application/src/ChatBubble.re
  examples/realtime-chat-application/src/Handler.re
  examples/realtime-chat-application/src/Header.re
  examples/realtime-chat-application/src/Messages.re
  examples/realtime-chat-application/src/MessagesContainer.re
  examples/realtime-chat-application/src/NewMessageNotification.re
  examples/realtime-chat-application/src/ReasonApolloClient.re
  examples/realtime-chat-application/src/Theme.re
  examples/realtime-chat-application/src/index.html
  examples/realtime-chat-application/src/index.re
  examples/realtime-chat-application/webpack.config.js
  examples/realtime-chat-application/yarn.lock
  examples/swapi/src/PersonByIdDelete.re
  package.json
Labels: docs
